
name: Build, Test, Pack, Zip, and Publish

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  build-test-pack:
    runs-on: windows-latest

    env:
      # Update to desired major.minor. This is the base version family.
      BASE_VERSION: "1.2"

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure tags/commits info is available when we expand logic later

      # 2. Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Change to your target version

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build solution
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 5. Run tests
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      # 6. Pack NuGet
      - name: Pack NuGet
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      # 7. Create ZIP of artifacts
      - name: Create ZIP archive
        run: |
          mkdir ./zip
          powershell Compress-Archive -Path ./artifacts/* -DestinationPath ./zip/artifacts.zip

      # 8. Upload ZIP as workflow artifact
      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package-zip
          path: ./zip/artifacts.zip
